---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  CONTROLLER_IMAGE_NAME: ghcr.io/xentra-ai/images/guardian-controller
  IMAGE_VERSION: local
  TARGET: x86_64-unknown-linux-gnu

tasks:
  all:
    desc: "Run all controller tasks"
    cmds:
      - task: controller:build
      - task: controller:install

  build:
    desc: "Build the controller with Cargo and cross"
    cmds:
      - cd controller && cargo xtask build-ebpf --release
      - cd controller && cross build --release --target {{.TARGET}}
      - mkdir -p localbin
      - cp controller/target/{{.TARGET}}/release/kube-guardian localbin
      - docker build -t {{.CONTROLLER_IMAGE_NAME}}:{{.IMAGE_VERSION}} . -f controller/docker/local.Dockerfile
      - kind load docker-image {{.CONTROLLER_IMAGE_NAME}}:{{.IMAGE_VERSION}}
      - rm -rf localbin

  install:
    desc: "Install Controller using Helm"
    cmds:
      - helm repo add xentra https://xentra-ai.github.io/charts || true
      - helm upgrade --install kube-guardian xentra/kube-guardian --namespace kube-guardian --create-namespace --set image.tag={{.IMAGE_VERSION}}

  install-oci:
    desc: "Install Controller using OCI Helm chart"
    cmds:
      - helm template kube-guardian oci://ghcr.io/xentra-ai/charts/kube-guardian --namespace kube-guardian --create-namespace

  preflight:
    desc: "Run preflight checks for Controller"
    cmds:
      - command -v cargo || echo "cargo is not installed"
      - command -v cross || echo "cross is not installed"
      - command -v docker || echo "docker is not installed"
      - command -v kind || echo "kind is not installed"
      - command -v helm || echo "helm is not installed"
