---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  CONTROLLER_IMAGE_NAME: ghcr.io/xentra-ai/images/guardian-controller
  IMAGE_VERSION: 0.8
  TARGET: x86_64-unknown-linux-gnu

tasks:
  all:
    desc: "Run all controller tasks"
    cmds:
      - task: build

  build:
    desc: "Build the controller with Cargo and cross"
    cmds:
      - cd controller && cross build --release --target {{.TARGET}}
      - mkdir -p localbin
      - cp controller/target/{{.TARGET}}/release/kube-guardian localbin
      - docker build -t {{.CONTROLLER_IMAGE_NAME}}:{{.IMAGE_VERSION}} . -f controller/Dockerfile
      - kind load docker-image {{.CONTROLLER_IMAGE_NAME}}:{{.IMAGE_VERSION}}
      - rm -rf localbin

  preflight:
    desc: "Run preflight checks for Controller"
    cmds:
      - command -v cargo || echo "cargo is not installed"
      - command -v cross || echo "cross is not installed"
      - command -v docker || echo "docker is not installed"
      - command -v kind || echo "kind is not installed"
      - command -v helm || echo "helm is not installed"
