apiVersion: v2
name: kguardian
description: Kubernetes security profile generator using eBPF
home: https://github.com/kguardian-dev/kguardian

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.0"
kubeVersion: ">= 1.18.0-0"

keywords:
  - BPF
  - eBPF
  - Kubernetes
  - Networking
  - Security
  - Observability
  - Troubleshooting

sources:
  - https://github.com/kguardian-dev/kguardian

maintainers:
  # Mahesh Rayas
  - name: maheshrayas
  # Michael Fornaro
  - name: xunholy
