---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

includes:
  advisor: .taskfiles/Advisor
  broker: .taskfiles/Broker
  controller: .taskfiles/Controller
  ui: .taskfiles/UI

vars:
  IMAGE_VERSION: local

tasks:
  all:
    deps: [kind]
    desc: "Run all tasks"
    cmds:
      #- task: advisor:all
      - task: broker:all
      - task: controller:all

  kind:
    desc: Create fresh kind cluster
    cmds:
      - kind delete cluster || true
      - kind create cluster

  install:
    deps: [all]
    desc: "Install in KinD cluster"
    cmds:
      - helm repo add xentra https://xentra-ai.github.io/kube-guardian || true
      - helm install kube-guardian xentra/kube-guardian --namespace kube-guardian
        --create-namespace --set controller.image.tag={{.IMAGE_VERSION}}
        --set broker.image.tag={{.IMAGE_VERSION}}
        --set controller.image.pullPolicy=IfNotPresent
        --set broker.image.pullPolicy=IfNotPresent

  preflight:
    desc: "Run preflight checks for all components"
    cmds:
      - task: advisor:preflight
      - task: broker:preflight
      - task: controller:preflight
      - task: ui:preflight

  preflight-all:
    desc: "Run preflight checks and then all tasks"
    cmds:
      - task: preflight
      - task: all
