---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

includes:
  advisor: .taskfiles/Advisor
  broker: .taskfiles/Broker
  controller: .taskfiles/Controller
  ui: .taskfiles/UI

vars:
  IMAGE_VERSION: local

tasks:
  all:
    deps: [kind]
    desc: "Run all tasks"
    cmds:
      #- task: advisor:all
      - task: broker:all
      - task: controller:all

  kind:
    desc: Create fresh kind cluster
    cmds:
      - kind delete cluster || true
      - kind create cluster

  install:
    deps: [all]
    desc: "Install in KinD cluster (local dev - uses local images)"
    cmds:
      - helm repo add kguardian https://kguardian-dev.github.io/kguardian || true
      - helm install kguardian kguardian/kguardian --namespace kguardian
        --create-namespace --set controller.image.tag={{.IMAGE_VERSION}}
        --set broker.image.tag={{.IMAGE_VERSION}}
        --set controller.image.pullPolicy=IfNotPresent
        --set broker.image.pullPolicy=IfNotPresent

  install:oci:
    desc: "Install from OCI registry (production-style install)"
    cmds:
      - helm install kguardian oci://ghcr.io/kguardian-dev/charts/kguardian
        --namespace kguardian --create-namespace

  preflight:
    desc: "Run preflight checks for all components"
    cmds:
      - task: advisor:preflight
      - task: broker:preflight
      - task: controller:preflight
      - task: ui:preflight

  preflight-all:
    desc: "Run preflight checks and then all tasks"
    cmds:
      - task: preflight
      - task: all
