package network

import (
	"fmt"

	"github.com/kguardian-dev/kguardian/advisor/pkg/api"
	"github.com/kguardian-dev/kguardian/advisor/pkg/common"
	log "github.com/rs/zerolog/log"
	networkingv1 "k8s.io/api/networking/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// CiliumPolicyGenerator generates Cilium NetworkPolicy resources
type CiliumPolicyGenerator struct {
	data BrokerData
}

// NewCiliumPolicyGenerator creates a new generator for Cilium NetworkPolicy
// resources, resolving peers via the default (api-backed) broker data source.
func NewCiliumPolicyGenerator() *CiliumPolicyGenerator {
	return &CiliumPolicyGenerator{data: DefaultBrokerData()}
}

func (g *CiliumPolicyGenerator) setBrokerData(d BrokerData) {
	if d != nil {
		g.data = d
	}
}

// broker returns the injected BrokerData, falling back to the default so a
// zero-value generator never nil-panics.
func (g *CiliumPolicyGenerator) broker() BrokerData {
	if g.data == nil {
		return DefaultBrokerData()
	}
	return g.data
}

// GetType returns the policy type
func (g *CiliumPolicyGenerator) GetType() PolicyType {
	return CiliumPolicy
}

// Generate creates a CiliumNetworkPolicy for the specified pod
//
// This uses the same corrected traffic processing logic as the standard policy generator
// but leverages Cilium's enhanced features like:
// - EndpointSelector with more flexible label matching
// - FromCIDR for external IP blocks
// - ToPorts with protocol specification
// - Better integration with service discovery
func (g *CiliumPolicyGenerator) Generate(podName string, podTraffic []api.PodTraffic, podDetail *api.PodDetail) (interface{}, error) {
	log.Info().Msgf("Generating Cilium network policy for pod %s", podName)

	if podDetail == nil {
		return nil, fmt.Errorf("pod detail is nil for pod %s", podName)
	}

	if len(podTraffic) == 0 {
		// If there's no traffic, generate a default-deny policy
		log.Warn().Msgf("No traffic data available for pod %s. Generating a default-deny Cilium policy.", podName)
		return g.generateDefaultDenyPolicy(podDetail), nil
	}

	// Process traffic using the same corrected logic as standard policy generator
	ingressRules, egressRules := g.processTrafficRules(podTraffic, podDetail)

	// Create the CiliumNetworkPolicy object
	policy := &CiliumNetworkPolicy{
		TypeMeta: CreateTypeMeta("CiliumNetworkPolicy", "cilium.io/v2"),
		ObjectMeta: CreateObjectMeta(
			GetPolicyName(podDetail.Name, "cilium-policy"),
			podDetail.Namespace,
			CreateStandardLabels(podDetail.Name, "cilium-policy"),
		),
		Spec: &CiliumRule{
			EndpointSelector: g.createEndpointSelector(podDetail.Pod.Labels),
			Description:      fmt.Sprintf("Cilium network policy for pod %s generated by kguardian", podDetail.Name),
		},
	}

	// Add ingress rules if any
	if len(ingressRules) > 0 {
		policy.Spec.Ingress = g.transformToCiliumIngressRules(ingressRules)
		log.Debug().Msgf("Added %d ingress rules to Cilium policy", len(policy.Spec.Ingress))
	}

	// Add egress rules if any
	if len(egressRules) > 0 {
		policy.Spec.Egress = g.transformToCiliumEgressRules(egressRules)
		log.Debug().Msgf("Added %d egress rules to Cilium policy", len(policy.Spec.Egress))
	}

	// If no rules were added, make it default deny
	if len(policy.Spec.Ingress) == 0 && len(policy.Spec.Egress) == 0 {
		log.Warn().Msgf("No valid ingress or egress rules generated for pod %s. Applying default-deny.", podName)
		return g.generateDefaultDenyPolicy(podDetail), nil
	}

	return policy, nil
}

// generateDefaultDenyPolicy creates a Cilium policy that denies all traffic
func (g *CiliumPolicyGenerator) generateDefaultDenyPolicy(podDetail *api.PodDetail) *CiliumNetworkPolicy {
	// Create bool pointers for DefaultDenyConfig
	truePtr := true

	return &CiliumNetworkPolicy{
		TypeMeta: CreateTypeMeta("CiliumNetworkPolicy", "cilium.io/v2"),
		ObjectMeta: CreateObjectMeta(
			GetPolicyName(podDetail.Name, "cilium-policy-deny-all"),
			podDetail.Namespace,
			CreateStandardLabels(podDetail.Name, "cilium-policy-deny-all"),
		),
		Spec: &CiliumRule{
			EndpointSelector: g.createEndpointSelector(podDetail.Pod.Labels),
			Description:      fmt.Sprintf("Default-deny Cilium network policy for pod %s", podDetail.Name),
			// Cilium default-deny behavior: empty ingress/egress rules with EnableDefaultDeny
			EnableDefaultDeny: &CiliumDefaultDeny{
				Ingress: &truePtr,
				Egress:  &truePtr,
			},
		},
	}
}

// processTrafficRules groups traffic rules by direction using the corrected logic
func (g *CiliumPolicyGenerator) processTrafficRules(podTraffic []api.PodTraffic, podDetail *api.PodDetail) ([]NetworkPolicyRule, []NetworkPolicyRule) {
	var ingressRules, egressRules []NetworkPolicyRule

	for _, traffic := range podTraffic {
		var portInt int
		var err error
		var peer string
		var port intstr.IntOrString
		var protocolStr string

		if IsIngressTraffic(traffic, podDetail) {
			// For INGRESS traffic: External peer -> Our Pod
			// - Peer is the source sending to us (traffic.DstIP - the external entity)
			// - Port is the port on our pod receiving the traffic (traffic.SrcPodPort)
			peer = traffic.DstIP

			// Skip if peer is empty or same as pod's own IP (self-traffic)
			if peer == "" {
				log.Debug().Msgf("Skipping ingress traffic with empty peer IP")
				continue
			}
			if peer == podDetail.PodIP {
				log.Debug().Msgf("Skipping ingress self-traffic (peer %s == pod IP %s)", peer, podDetail.PodIP)
				continue
			}

			portInt, err = parsePort(traffic.SrcPodPort)
			if err != nil {
				log.Warn().Err(err).Msgf("Skipping ingress traffic record due to invalid pod port: %s", traffic.SrcPodPort)
				continue
			}
			port = intstr.FromInt(portInt)
			protocolStr = string(traffic.Protocol)

			log.Debug().Msgf("Processing CILIUM INGRESS: allowing peer %s to reach our pod port %d (%s)", peer, portInt, protocolStr)
			ingressRules = g.addOrUpdateRule(ingressRules, peer, port, protocolStr)

		} else if IsEgressTraffic(traffic, podDetail) {
			// For EGRESS traffic: Our Pod -> External destination
			// - Peer is the destination (traffic.DstIP - where our pod is connecting to)
			// - Port is the destination port (traffic.DstPort - the port on the target service/pod)
			peer = traffic.DstIP

			// Skip if peer is empty or same as pod's own IP (self-traffic)
			if peer == "" {
				log.Debug().Msgf("Skipping egress traffic with empty peer IP")
				continue
			}
			if peer == podDetail.PodIP {
				log.Debug().Msgf("Skipping egress self-traffic (peer %s == pod IP %s)", peer, podDetail.PodIP)
				continue
			}

			portInt, err = parsePort(traffic.DstPort)
			if err != nil {
				log.Warn().Err(err).Msgf("Skipping egress traffic record due to invalid destination port: %s", traffic.DstPort)
				continue
			}
			port = intstr.FromInt(portInt)
			protocolStr = string(traffic.Protocol)

			log.Debug().Msgf("Processing CILIUM EGRESS: allowing our pod to reach peer %s on port %d (%s)", peer, portInt, protocolStr)
			egressRules = g.addOrUpdateRule(egressRules, peer, port, protocolStr)
		} else {
			log.Debug().Msgf("Skipping traffic record with unknown type: %s", traffic.TrafficType)
		}
	}

	log.Info().Msgf("Generated %d ingress rules and %d egress rules for Cilium policy of pod %s",
		len(ingressRules), len(egressRules), podDetail.Name)

	return ingressRules, egressRules
}

// addOrUpdateRule delegates to the shared mergeOrAppendRule helper.
// Kept as a method for backwards compatibility with existing tests +
// call sites; the underlying logic lives in types.go so both generators
// stay in lockstep.
func (g *CiliumPolicyGenerator) addOrUpdateRule(rules []NetworkPolicyRule, peer string, port intstr.IntOrString, protocolStr string) []NetworkPolicyRule {
	return mergeOrAppendRule(rules, peer, port, protocolStr)
}

// createEndpointSelector creates a Cilium EndpointSelector from pod labels.
//
// Iterates the input map in sorted-key order so the resulting
// LabelArray (a slice) is byte-identical across regenerations of the
// same policy. Without the sort, Go's randomised map iteration meant
// the order in which labels were appended depended on map-hash state
// — different across processes and even across edits to the labels
// themselves. The downstream NewESFromLabels preserves slice order
// in some of its internal representations, so emit positions in the
// generated YAML could drift between runs, surfacing as spurious
// kubectl/git diffs even for label sets that didn't change. Same UX-
// stability class as the peer-IP and port-list sorts.
//
// The standard generator's createNetworkPolicyPeer side doesn't need
// this fix: it constructs metav1.LabelSelector.MatchLabels (a Go map),
// and Go's JSON encoder sorts map keys, so the output YAML is already
// deterministic there.
func (g *CiliumPolicyGenerator) createEndpointSelector(podLabels map[string]string) CiliumEndpointSelector {
	if len(podLabels) == 0 {
		log.Warn().Msg("Pod has no labels, using empty EndpointSelector")
	}
	// newCiliumEndpointSelector applies the "k8s:" label-source prefix. Output
	// determinism is free: matchLabels is a Go map and the JSON encoder sorts
	// map keys, so regenerating the same policy yields identical YAML without
	// the explicit key sort the old LabelArray path needed.
	return newCiliumEndpointSelector(podLabels)
}

// transformToCiliumIngressRules converts our internal rules to Cilium IngressRule
func (g *CiliumPolicyGenerator) transformToCiliumIngressRules(rules []NetworkPolicyRule) []CiliumIngressRule {
	var ingressRules []CiliumIngressRule

	// Group rules by peer IP
	peerRules := make(map[string][]networkingv1.NetworkPolicyPort)
	for _, rule := range rules {
		peerRules[rule.PeerIP] = append(peerRules[rule.PeerIP], rule.Ports...)
	}

	// Iterate in sorted peer-IP order — see sortedKeys in
	// standard_policy.go for the determinism rationale. Same fix
	// class applies to Cilium output: regenerating the same policy
	// must produce identical YAML so kubectl diff is clean.
	for _, peerIP := range sortedKeys(peerRules) {
		ports := peerRules[peerIP]
		ingressRule := g.createCiliumIngressRuleForPeer(peerIP, ports)
		if ingressRule != nil {
			ingressRules = append(ingressRules, *ingressRule)
		}
	}

	return ingressRules
}

// transformToCiliumEgressRules converts our internal rules to Cilium EgressRule
func (g *CiliumPolicyGenerator) transformToCiliumEgressRules(rules []NetworkPolicyRule) []CiliumEgressRule {
	var egressRules []CiliumEgressRule

	// Group rules by peer IP
	peerRules := make(map[string][]networkingv1.NetworkPolicyPort)
	for _, rule := range rules {
		peerRules[rule.PeerIP] = append(peerRules[rule.PeerIP], rule.Ports...)
	}

	// Sorted iteration — see ingress sibling.
	for _, peerIP := range sortedKeys(peerRules) {
		ports := peerRules[peerIP]
		egressRule := g.createCiliumEgressRuleForPeer(peerIP, ports)
		if egressRule != nil {
			egressRules = append(egressRules, *egressRule)
		}
	}

	return egressRules
}

// createCiliumIngressRuleForPeer creates a Cilium ingress rule for a specific peer
func (g *CiliumPolicyGenerator) createCiliumIngressRuleForPeer(peerIP string, ports []networkingv1.NetworkPolicyPort) *CiliumIngressRule {
	log.Debug().Msgf("Creating Cilium ingress rule for peer IP: %s", peerIP)

	// Try to resolve peer information
	fromEndpoints, fromCIDR := g.resolvePeerForCilium(peerIP)

	var ingressRule CiliumIngressRule

	// Set the peer selector
	if len(fromEndpoints) > 0 {
		ingressRule.FromEndpoints = fromEndpoints
		log.Debug().Msgf("Using FromEndpoints for peer %s", peerIP)
	} else if len(fromCIDR) > 0 {
		ingressRule.FromCIDR = fromCIDR
		log.Debug().Msgf("Using FromCIDR for peer %s", peerIP)
	} else {
		log.Warn().Msgf("Could not resolve peer %s, skipping rule", peerIP)
		return nil
	}

	// Convert ports to Cilium PortRules
	ingressRule.ToPorts = g.convertPortsToCiliumPortRules(ports)

	return &ingressRule
}

// createCiliumEgressRuleForPeer creates a Cilium egress rule for a specific peer
func (g *CiliumPolicyGenerator) createCiliumEgressRuleForPeer(peerIP string, ports []networkingv1.NetworkPolicyPort) *CiliumEgressRule {
	log.Debug().Msgf("Creating Cilium egress rule for peer IP: %s", peerIP)

	// Try to resolve peer information
	toEndpoints, toCIDR := g.resolvePeerForCilium(peerIP)

	var egressRule CiliumEgressRule

	// Set the peer selector
	if len(toEndpoints) > 0 {
		egressRule.ToEndpoints = toEndpoints
		log.Debug().Msgf("Using ToEndpoints for peer %s", peerIP)
	} else if len(toCIDR) > 0 {
		egressRule.ToCIDR = toCIDR
		log.Debug().Msgf("Using ToCIDR for peer %s", peerIP)
	} else {
		log.Warn().Msgf("Could not resolve peer %s, skipping rule", peerIP)
		return nil
	}

	// Convert ports to Cilium PortRules
	egressRule.ToPorts = g.convertPortsToCiliumPortRules(ports)

	return &egressRule
}

// resolvePeerForCilium resolves peer IP to either EndpointSelector or CIDR
func (g *CiliumPolicyGenerator) resolvePeerForCilium(peerIP string) ([]CiliumEndpointSelector, []string) {
	// Try to get Service info first
	svcSpec, err := g.broker().ServiceByIP(peerIP)
	if err == nil && svcSpec != nil && len(svcSpec.Service.Spec.Selector) > 0 {
		log.Debug().Msgf("Found service %s/%s with selector %v for IP %s",
			svcSpec.SvcNamespace, svcSpec.SvcName, svcSpec.Service.Spec.Selector, peerIP)

		// Create EndpointSelector from service labels
		selector := g.createEndpointSelector(svcSpec.Service.Spec.Selector)
		return []CiliumEndpointSelector{selector}, nil
	}

	// Try to get Pod info
	podSpec, err := g.broker().PodByIP(peerIP)
	if err == nil && podSpec != nil && len(podSpec.Pod.Labels) > 0 {
		log.Debug().Msgf("Found pod %s/%s with labels %v for IP %s",
			podSpec.Namespace, podSpec.Name, podSpec.Pod.Labels, peerIP)

		// Create EndpointSelector from pod labels
		selector := g.createEndpointSelector(podSpec.Pod.Labels)
		return []CiliumEndpointSelector{selector}, nil
	}

	// Fall back to CIDR for external IPs or unresolvable cluster IPs.
	//
	// common.HostCIDR picks the prefix length from the address family
	// (/32 for IPv4, /128 for IPv6) — this used to be a hardcoded "/32",
	// which on a dual-stack cluster widened a single peer into the whole
	// fd00::/32 block. Returning both selectors empty is the existing
	// "could not resolve peer" signal: transformToCilium{Ingress,Egress}Rules
	// already logs and drops the rule rather than emitting one with no
	// peer, so an unparseable address costs that single rule instead of
	// putting a malformed toCIDR entry into the policy.
	cidr, err := common.HostCIDR(peerIP)
	if err != nil {
		log.Warn().Err(err).Msgf("Skipping peer %s: cannot express it as a host CIDR", peerIP)
		return nil, nil
	}
	log.Debug().Msgf("Using CIDR %s for peer %s", cidr, peerIP)
	return nil, []string{cidr}
}

// convertPortsToCiliumPortRules converts standard ports to Cilium PortRules.
//
// Routes the input through deduplicatePorts first so:
//   - Duplicate (port, protocol) pairs from the broker — common when
//     /pod/traffic/{name} returns multiple events for the same flow —
//     don't leak into the generated YAML as redundant PortRule entries.
//   - The output ordering is deterministic (port ASC, protocol ASC, named
//     after numeric). Without this, the Cilium YAML's ToPorts/FromPorts
//     list reshuffles between regenerations of the same input, producing
//     spurious kubectl/git diffs — same UX problem the standard generator
//     hit in 87bb514e.
//
// `ports` from the caller is the per-peer ports slice built by
// transformToCilium{Ingress,Egress}Rules, which had no dedup/sort —
// previously each call wrote duplicate PortRule entries verbatim.
// The nil-port/nil-protocol skip below is now redundant (the dedup
// helper handles it) but kept as a defense-in-depth assertion: any
// future refactor that bypasses dedup still won't crash on nil deref.
func (g *CiliumPolicyGenerator) convertPortsToCiliumPortRules(ports []networkingv1.NetworkPolicyPort) []CiliumPortRule {
	deduped := deduplicatePorts(ports)
	portRules := make([]CiliumPortRule, 0, len(deduped))

	for _, port := range deduped {
		if port.Port == nil || port.Protocol == nil {
			log.Warn().Msg("Skipping port with nil port or protocol")
			continue
		}

		portRule := CiliumPortRule{
			Ports: []CiliumPortProtocol{
				{
					Port:     port.Port.String(),
					Protocol: string(*port.Protocol),
				},
			},
		}
		portRules = append(portRules, portRule)
	}

	return portRules
}
