{{- if and .Values.database.persistence.enabled (not .Values.database.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.name }}-data
  labels:
    {{- include "kguardian.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.database.service.name }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.database.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.database.persistence.size | default "10Gi" }}
{{- end }}
