---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.service.name }}
  labels:
    {{- include "kguardian.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      # targetPort: postgresdb
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.database.service.name }}
