DROP INDEX IF EXISTS idx_vuln_cve_summary_tier;
ALTER TABLE vuln_cve_summary DROP COLUMN IF EXISTS exposed_workloads;
ALTER TABLE vuln_cve_summary DROP COLUMN IF EXISTS not_observed_workloads;
ALTER TABLE vuln_cve_summary DROP COLUMN IF EXISTS unknown_workloads;
ALTER TABLE vuln_cve_summary DROP COLUMN IF EXISTS loaded_workloads;
ALTER TABLE vuln_cve_summary DROP COLUMN IF EXISTS executed_workloads;
ALTER TABLE vuln_cve_summary DROP COLUMN IF EXISTS in_use;
ALTER TABLE vuln_cve_summary DROP COLUMN IF EXISTS tier;
DROP FUNCTION IF EXISTS kg_in_use_rank(text);
DROP FUNCTION IF EXISTS kg_pkg_in_use(text, text, text, text, text, text, text, boolean);
DROP INDEX IF EXISTS idx_image_sbom_components_name;
DROP FUNCTION IF EXISTS kg_pkg_observable(text, text);
DROP FUNCTION IF EXISTS kg_vuln_tier(text, smallint, boolean, real, boolean, boolean, double precision, boolean);
DROP TABLE IF EXISTS workload_network_exposure;
DROP TABLE IF EXISTS runtime_in_use_coverage;
DROP TABLE IF EXISTS runtime_unowned_paths;
DROP TABLE IF EXISTS runtime_package_use;
