import { useEffect, useState } from 'react';
import { AlertTriangle, Check, Copy, Download } from 'lucide-react';
import type { VulnApi } from '../../services/vulnApi';
import { vulnErrorMessage } from '../../services/vulnApi';
import type { AdmissionFormat } from '../../types/attestations';
import { copyText } from '../../utils/clipboard';
import { splitHeader } from '../../utils/signatures';
import { Modal } from '../ui/Modal';
import { Button } from '../ui/Button';
import { SectionSkeleton } from '../Profile/parts';
import { VulnErrorState } from './parts';

/** Where the policy comes from: the cluster (or one namespace) or one workload's export bundle. */
export type AdmissionScope = { kind: 'cluster'; namespace?: string } | { kind: 'workload'; namespace: string; workloadKind: string; name: string };

const FORMATS: Array<{ id: AdmissionFormat; label: string; what: string }> = [
  { id: 'kguardian', label: 'kguardian ImageTrustPolicy', what: 'Report only: the kguardian evaluator writes would-deny containers to the policy status.' },
  { id: 'kyverno', label: 'Kyverno ImageValidatingPolicy', what: 'validationActions [Audit]: failures go to policy reports, nothing is denied.' },
  { id: 'policy-controller', label: 'Sigstore ClusterImagePolicy', what: 'mode warn: policy-controller admits and warns (it has no audit-only mode).' },
];

type Doc = { status: 'loading' } | { status: 'error'; error: unknown } | { status: 'unavailable'; reason: string } | { status: 'ok'; text: string; fileName: string };

function download(filename: string, content: string) {
  const url = URL.createObjectURL(new Blob([content], { type: 'text/yaml' }));
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** A header line's role: the review warning, an identity, what it was seen on, or an image left out. */
function headerTone(line: string): string {
  if (line.startsWith('REVIEW EVERY IDENTITY') || line.startsWith('A signer that signed')) return 'text-severity-medium font-semibold';
  if (line.startsWith('identity:')) return 'text-primary';
  if (line.startsWith('not covered:')) return 'text-secondary';
  return 'text-tertiary';
}

/**
 * Export an image admission policy, audit mode only: generated by the
 * Broker from the signers kguardian verified on running images. The
 * Broker's header is shown as it is, above the YAML: every identity it
 * lists was observed, not vetted, and must be reviewed before applying.
 * kguardian never applies anything.
 */
export function AdmissionPolicyModal({ api, scope, onClose }: { api: VulnApi; scope: AdmissionScope; onClose: () => void }) {
  const [format, setFormat] = useState<AdmissionFormat>('kguardian');
  const [doc, setDoc] = useState<Doc>({ status: 'loading' });
  const [copied, setCopied] = useState(false);
  const [attempt, setAttempt] = useState(0);

  useEffect(() => {
    let live = true;
    // eslint-disable-next-line react-hooks/set-state-in-effect -- a new read on format / retry
    setDoc({ status: 'loading' });
    const read = async (): Promise<Doc> => {
      if (scope.kind === 'cluster') {
        const text = await api.admissionPolicy({ format, namespace: scope.namespace });
        return { status: 'ok', text, fileName: `image-admission-${scope.namespace ?? 'cluster'}-${format}.yaml` };
      }
      const m = await api.workloadAdmission(scope.namespace, scope.workloadKind, scope.name);
      const d = m.documents.find((x) => x.artifact === 'admission');
      if (!d) return { status: 'unavailable', reason: 'The Broker returned no admission document for this workload.' };
      if (!d.available || !d.content) return { status: 'unavailable', reason: d.refused ?? d.reason ?? 'Not available.' };
      return { status: 'ok', text: d.content, fileName: `${scope.name}-${d.fileName}` };
    };
    read().then(
      (d) => live && setDoc(d),
      (error: unknown) => live && setDoc({ status: 'error', error }),
    );
    return () => {
      live = false;
    };
  }, [api, scope, format, attempt]);

  const text = doc.status === 'ok' ? doc.text : null;
  const parts = text ? splitHeader(text) : null;
  const target = scope.kind === 'workload' ? `${scope.namespace}/${scope.workloadKind}/${scope.name}` : scope.namespace ? `namespace ${scope.namespace}` : 'the cluster';

  return (
    <Modal
      isOpen
      onClose={onClose}
      size="lg"
      title="Export admission policy"
      subtitle={`${target} · audit mode · kguardian never applies anything: review, commit and apply it yourself.`}
      className="h-[85vh]"
      contentClassName="flex-1 min-h-0 overflow-y-auto"
      footer={
        <>
          <Button variant="ghost" size="sm" onClick={onClose}>Close</Button>
          <Button
            variant="secondary"
            size="sm"
            leftIcon={copied ? Check : Copy}
            disabled={!text}
            onClick={async () => {
              if (text && (await copyText(text))) {
                setCopied(true);
                setTimeout(() => setCopied(false), 2000);
              }
            }}
          >
            {copied ? 'Copied' : 'Copy YAML'}
          </Button>
          <Button variant="primary" size="sm" leftIcon={Download} disabled={!text} onClick={() => text && doc.status === 'ok' && download(doc.fileName, text)}>
            Download YAML
          </Button>
        </>
      }
    >
      <div className="px-4 sm:px-5 py-4 space-y-4">
        {scope.kind === 'cluster' ? (
          <fieldset className="space-y-1.5">
            <legend className="text-xs font-medium text-secondary mb-1">Policy engine</legend>
            {FORMATS.map((f) => (
              <label key={f.id} className="flex items-start gap-2 text-xs cursor-pointer">
                <input type="radio" name="admission-format" value={f.id} checked={format === f.id} onChange={() => setFormat(f.id)} className="mt-0.5" />
                <span>
                  <span className="text-primary">{f.label}</span>
                  <span className="block text-tertiary">{f.what}</span>
                </span>
              </label>
            ))}
          </fieldset>
        ) : (
          <p className="text-xs text-tertiary">The admission artifact of this workload&apos;s export bundle: a namespaced kguardian ImageTrustPolicy in audit mode (report only).</p>
        )}

        {doc.status === 'loading' && <SectionSkeleton rows={4} />}
        {doc.status === 'error' && <VulnErrorState error={doc.error} unsupportedTitle="Policy generation not available" onRetry={() => setAttempt((n) => n + 1)} />}
        {doc.status === 'unavailable' && (
          <div role="status" className="flex items-start gap-2 rounded-control border border-dashed border-hubble-border-strong px-3 py-2.5 text-xs text-secondary">
            <AlertTriangle className="w-4 h-4 shrink-0 text-severity-medium" aria-hidden />
            <span>No policy was generated: {doc.reason}</span>
          </div>
        )}
        {parts && (
          <>
            {parts.header.length > 0 && (
              <section aria-label="Policy header: review before applying" className="rounded-control border border-severity-medium/40 bg-severity-medium/5 px-3 py-2.5">
                <ul className="space-y-0.5 font-mono text-[11px] leading-5 [overflow-wrap:anywhere]">
                  {parts.header.map((l, i) => (
                    <li key={i} className={headerTone(l)}>{l || ' '}</li>
                  ))}
                </ul>
              </section>
            )}
            <pre aria-label="Policy YAML" className="rounded-control border border-hubble-border bg-hubble-hover/20 px-3 py-2.5 text-xs font-mono text-secondary overflow-x-auto whitespace-pre">
              {parts.body}
            </pre>
          </>
        )}
        {doc.status === 'error' && <p className="text-[11px] text-tertiary">{vulnErrorMessage(doc.error)}</p>}
      </div>
    </Modal>
  );
}
