[package]
name = "kube-guardian"
version = "0.1.0"
license = "LGPL-2.1-only OR BSD-2-Clause"
edition = "2021"

[build-dependencies]
libbpf-cargo = "0.24.1"

[dependencies]
anyhow = "1.0.4"
libbpf-rs = "0.24.1"
libbpf-sys = "1.4.3"
plain = "0.2"
time = { version = "0.3", features = ["formatting", "local-offset", "macros"]}
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread", "fs"] }
kube = { version = "0.93.1", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.22.0", features = ["latest"] }
futures = "0.3.25"
thiserror = "1.0.37"
tracing = "0.1.37"
serde = "1.0.114"
serde_derive = "1.0.114"
serde_json = "1.0.93"
tracing-subscriber = { version = "0.3.16", features = ["json", "env-filter", "local-time"] }
containerd-client = { git = "https://github.com/containerd/rust-extensions", branch = "main" }
regex = "1.7.3"
procfs = "0.17.0"
reqwest = "0.12.5"
uuid = { version = "1.3.4", features = ["v4"]}
chrono = { version = "0.4.23", features = ["serde"] }
openssl = { version = "0.10", features = ["vendored"] }
lazy_static = "1.5.0"