#!/usr/bin/env python3
"""Write a Spring Boot layout fat jar: nested library jars from Maven
Central under BOOT-INF/lib (log4j-core among them, the case the design
calls out), application classes under BOOT-INF/classes, and the Boot
manifest."""
import sys
import urllib.request
import zipfile

LIBS = [
    "org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar",
    "org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar",
    "org/springframework/spring-core/6.1.14/spring-core-6.1.14.jar",
    "org/springframework/spring-jcl/6.1.14/spring-jcl-6.1.14.jar",
    "org/yaml/snakeyaml/2.2/snakeyaml-2.2.jar",
]
BASE = "https://repo1.maven.org/maven2/"

MANIFEST = """Manifest-Version: 1.0
Main-Class: org.springframework.boot.loader.launch.JarLauncher
Start-Class: com.example.demo.DemoApplication
Spring-Boot-Version: 3.3.5
Spring-Boot-Classes: BOOT-INF/classes/
Spring-Boot-Lib: BOOT-INF/lib/
Implementation-Title: demo
Implementation-Version: 0.0.1-SNAPSHOT

"""

POM = """#Generated by Maven
groupId=com.example
artifactId=demo
version=0.0.1-SNAPSHOT
"""


def main(out):
    with zipfile.ZipFile(out, "w", compression=zipfile.ZIP_DEFLATED) as z:
        z.writestr("META-INF/MANIFEST.MF", MANIFEST)
        z.writestr("META-INF/maven/com.example/demo/pom.properties", POM)
        z.writestr("BOOT-INF/classes/com/example/demo/DemoApplication.class", b"\xca\xfe\xba\xbe")
        for lib in LIBS:
            with urllib.request.urlopen(BASE + lib, timeout=60) as r:
                data = r.read()
            # Nested jars are stored uncompressed, as Spring Boot requires.
            info = zipfile.ZipInfo("BOOT-INF/lib/" + lib.rsplit("/", 1)[1])
            info.compress_type = zipfile.ZIP_STORED
            z.writestr(info, data)


if __name__ == "__main__":
    main(sys.argv[1])
