name: Build and Push Broker Docker Images 

on:
  workflow_dispatch: {}
  push:
    paths:
      - '.github/workflows/broker.yaml'
      - 'broker/broker.Dockerfile'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          version: latest

      - name: Login to GHCR
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: broker/
          file: broker/broker.Dockerfile
          platforms: linux/amd64 #,linux/arm64
          push: true
          tags: |
            ghcr.io/xentra-ai/images/guardian-broker:latest
