name: Build and Test Go

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-go.yaml
      - '**/*.go'
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/build-go.yaml
      - '**/*.go'

permissions:
  contents: read

defaults:
  run:
    working-directory: ./advisor

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3
        with:
          version: latest
          working-directory: ./advisor
          args: --timeout=5m

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    strategy:
      matrix:
        go-version: [ '1.21.x' ]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go get -v ./...

      - name: Build
        run: go build -v ./...

      - name: Test with the Go CLI
        run: go test -v ./... > test-results-${{ matrix.go-version }}.json

      - name: Upload Go test results
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: test-results-${{ matrix.go-version }}
          path: test-results-${{ matrix.go-version }}.json
