name: Build and Push Docker Images

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-docker.yaml
      - advisor/Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3
        with:
          install: true
          version: latest

      - name: Login to GHCR
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        if: github.ref != 'refs/heads/master'
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5
        with:
          build-args: |
            APPLICATION_NAME=advisor
            VERSION=0.0.4
            SHA=${{ github.sha }}
          context: ./advisor
          file: ./advisor/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/xentra-ai/images/advisor:${{ github.sha }}
            ghcr.io/xentra-ai/images/advisor:latest
