name: "Charts: Release to GHCR OCI"

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - ".github/workflows/charts-release-ghpages.yaml"
      - "charts/**"

env:
  CHARTS_SRC_DIR: "kube-guardian"
  TARGET_REGISTRY: ghcr.io

jobs:
  release-charts:
    name: Release Charts
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.TARGET_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          # REQUIRED: We don't want this to override latest when the latest is used by the quick-install.sh for the advisor client
          mark_as_latest: false
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Publish Helm Chart to GHCR
        run: |
          helm package charts/${{ env.CHARTS_SRC_DIR }}
          helm push ${{ env.CHARTS_SRC_DIR }}-*.tgz oci://${{ env.TARGET_REGISTRY }}/${{ github.repository_owner }}/charts
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
