name: "Charts: Release to GHCR OCI"

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - '.github/workflows/charts-release-ghpages.yaml'
      - 'charts/**'

env:
  CHARTS_SRC_DIR: "kube-guardian"
  TARGET_REGISTRY: ghcr.io

jobs:
  release-charts:
    name: Release Charts
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.TARGET_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: ${{ env.CHARTS_SRC_DIR }}
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Publish Helm Chart to GHCR
        run: |
          helm package charts/kube-guardian
          helm push kube-guardian-*.tgz oci://${{ env.TARGET_REGISTRY }}/${{ github.repository_owner }}/charts
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
